name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/mapa_1.png
  - assets/vectors/capa_1_x2.svg
  - assets/images/mapa_1.png
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/home_1_x2.svg
  - assets/vectors/vector_134_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/vector_219_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_188_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_177_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_117_x2.svg
  - assets/vectors/vector_212_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_158_x2.svg
  - assets/vectors/vector_84_x2.svg
  - assets/vectors/vector_169_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/fundo_1_x2.svg
  - assets/vectors/icon_mobile_signal_6_x2.svg
  - assets/vectors/vector_213_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_120_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_154_x2.svg
  - assets/vectors/vector_172_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/vector_146_x2.svg
  - assets/vectors/vector_114_x2.svg
  - assets/vectors/vector_209_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_96_x2.svg
  - assets/vectors/vector_122_x2.svg
  - assets/vectors/wifi_4_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_133_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_stroke_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/vector_190_x2.svg
  - assets/vectors/vector_108_x2.svg
  - assets/images/mapa_1.png
  - assets/vectors/vector_118_x2.svg
  - assets/vectors/vector_99_x2.svg
  - assets/vectors/wifi_6_x2.svg
  - assets/vectors/vector_189_x2.svg
  - assets/vectors/vector_132_x2.svg
  - assets/vectors/vector_124_x2.svg
  - assets/vectors/vector_161_x2.svg
  - assets/vectors/vector_126_x2.svg
  - assets/vectors/vector_215_x2.svg
  - assets/vectors/vector_214_x2.svg
  - assets/vectors/vector_170_x2.svg
  - assets/vectors/vector_130_x2.svg
  - assets/vectors/vector_201_x2.svg
  - assets/vectors/home_4_x2.svg
  - assets/vectors/vector_191_x2.svg
  - assets/vectors/vector_115_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_206_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_166_x2.svg
  - assets/vectors/vector_173_x2.svg
  - assets/vectors/fundo_3_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_107_x2.svg
  - assets/vectors/vector_106_x2.svg
  - assets/vectors/battery_3_x2.svg
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/vector_145_x2.svg
  - assets/vectors/vector_140_x2.svg
  - assets/vectors/vector_202_x2.svg
  - assets/vectors/vector_112_x2.svg
  - assets/vectors/vector_208_x2.svg
  - assets/vectors/vector_178_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/vector_91_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/vector_148_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_217_x2.svg
  - assets/vectors/vector_stroke_4_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/icon_mobile_signal_1_x2.svg
  - assets/vectors/vector_164_x2.svg
  - assets/vectors/vector_192_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_103_x2.svg
  - assets/vectors/vector_203_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/vector_144_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/vector_157_x2.svg
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/vectors/vector_218_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_197_x2.svg
  - assets/vectors/vector_221_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_165_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_187_x2.svg
  - assets/vectors/vector_198_x2.svg
  - assets/vectors/vector_131_x2.svg
  - assets/vectors/vector_163_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_159_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/images/mapa_1.png
  - assets/vectors/vector_stroke_1_x2.svg
  - assets/vectors/battery_6_x2.svg
  - assets/vectors/fundo_4_x2.svg
  - assets/vectors/wifi_3_x2.svg
  - assets/vectors/icon_mobile_signal_3_x2.svg
  - assets/vectors/vector_136_x2.svg
  - assets/vectors/vector_216_x2.svg
  - assets/vectors/home_x2.svg
  - assets/images/mapa_1.png
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/fundo_x2.svg
  - assets/vectors/icon_mobile_signal_4_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/wifi_5_x2.svg
  - assets/vectors/battery_5_x2.svg
  - assets/vectors/back_1_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/images/mapa_1.png
  - assets/vectors/vector_184_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/vector_199_x2.svg
  - assets/vectors/vector_137_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/battery_4_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/icon_mobile_signal_2_x2.svg
  - assets/vectors/vector_210_x2.svg
  - assets/vectors/vector_179_x2.svg
  - assets/vectors/vector_142_x2.svg
  - assets/vectors/vector_stroke_2_x2.svg
  - assets/vectors/vector_110_x2.svg
  - assets/vectors/vector_129_x2.svg
  - assets/vectors/vector_194_x2.svg
  - assets/vectors/vector_105_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_101_x2.svg
  - assets/vectors/vector_135_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_121_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/vector_109_x2.svg
  - assets/vectors/vector_102_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/fundo_2_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_220_x2.svg
  - assets/vectors/vector_147_x2.svg
  - assets/vectors/wifi_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_207_x2.svg
  - assets/vectors/vector_171_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/vector_185_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/home_3_x2.svg
  - assets/vectors/vector_204_x2.svg
  - assets/vectors/vector_151_x2.svg
  - assets/vectors/vector_123_x2.svg
  - assets/vectors/vector_211_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/images/mapa_1.png
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_143_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/vector_128_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/vectors/vector_162_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/wifi_7_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/vector_83_x2.svg
  - assets/vectors/vector_176_x2.svg
  - assets/vectors/vector_127_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/vector_160_x2.svg
  - assets/vectors/vector_174_x2.svg
  - assets/vectors/vector_113_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/vector_196_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/vectors/battery_7_x2.svg
  - assets/vectors/vector_195_x2.svg
  - assets/vectors/vector_155_x2.svg
  - assets/vectors/vector_98_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/home_2_x2.svg
  - assets/vectors/vector_149_x2.svg
  - assets/vectors/vector_167_x2.svg
  - assets/vectors/vector_182_x2.svg
  - assets/vectors/vector_119_x2.svg
  - assets/vectors/icon_mobile_signal_5_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/vector_168_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/vector_205_x2.svg
  - assets/vectors/vector_104_x2.svg
  - assets/vectors/vector_139_x2.svg
  - assets/vectors/vector_138_x2.svg
  - assets/vectors/vector_111_x2.svg
  - assets/vectors/vector_stroke_3_x2.svg
  - assets/vectors/vector_152_x2.svg
  - assets/vectors/vector_116_x2.svg
  - assets/vectors/vector_193_x2.svg
  - assets/vectors/vector_156_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_200_x2.svg
  - assets/vectors/vector_181_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_80_x2.svg
  - assets/vectors/vector_150_x2.svg
  - assets/vectors/vector_175_x2.svg
  - assets/vectors/icon_mobile_signal_x2.svg
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/vector_153_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/vector_141_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_186_x2.svg
  - assets/vectors/battery_2_x2.svg
  - assets/vectors/vector_180_x2.svg
  - assets/vectors/vector_183_x2.svg
  - assets/vectors/back_x2.svg
  - assets/vectors/vector_125_x2.svg

